name: 'Test Python Environment'
description: 'Composite action to setup Python, install deps and run tests'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  app-path:
    description: 'Path to the application folder'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies, run app and test
      shell: bash
      run: |
        # Dynamicznie szukamy folderu bez względu na wielkość liter Lab_9 / lab_9
        TARGET_DIR=$(find . -iname "app_419912" -type d -print -quit)
        
        if [ -z "$TARGET_DIR" ]; then
          echo "ERROR: Nie znaleziono folderu app_419912!"
          exit 1
        fi
        
        echo "Znaleziono ścieżkę aplikacji: $TARGET_DIR"
        cd "$TARGET_DIR"
        
        # 1. Instalacja
        pip install -r requirements.txt
        
        # 2. Uruchomienie w tle
        python app.py &
        echo "Czekam na uruchomienie aplikacji..."
        for i in {1..10}; do
          curl -s http://localhost:5000/health && break
          sleep 2
        done
        
        # 3. Testy
        python -m pytest test_app.py -v