name: CI_123456  # Twoja nazwa

on:
  push:
    branches:
      - 'lab_7/new_branch_123456' # NAPRAWA 1: Tylko Twój branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Lab_7/app_123456/requirements.txt # NAPRAWA 2: Instalacja paczek

      - name: Run app and tests
        run: |
          cd Lab_7/app_123456
          python calculator.py & # Uruchomienie aplikacji w tle
          sleep 2               # Chwila na wystartowanie serwera
          python -m pytest test_calculator.py -v # NAPRAWA 3: Poprawna ścieżka do folderu