name: Test Python Environment 419534
description: Composite action for setting up Python, installing dependencies and running tests

inputs:
  python-version:
    description: Python version used in workflow
    required: true
  app-path:
    description: Path to tested application
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run tests
      shell: bash
      run: |
        cd ${{ inputs.app-path }}
        pip install -r requirements.txt
        python app.py &
        sleep 3
        python -m pytest test_app.py -v
        kill %1
