name: lab_7

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run tests
        run: |
           cd Lab_7/app_420007
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          python -m pytest test_api.py -v
