name: CI — Build, Test, Push

on:
  push:
    branches: [projekt_422375]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Uruchom testy
        run: |
          cd Projekt
          pip install -r requirements.txt
          pytest

      - name: Zaloguj się do ACR
        uses: azure/docker-login@v1
        with:
          login-server: acrlab03tadlesz3.azurecr.io
          username: acrlab03tadlesz3
          password: Y8sp0VgKJWLR6sUe9vBTaivBJmQKEewgBZsJTEed0V9WRJJLM8OaJQQJ99CFACE1PydEqg7NAAACAZCRzhrT

      - name: Zbuduj i wypchnij obraz
        run: |
          IMAGE=acrlab03tadlesz3.azurecr.io/app:${{ github.sha }}
          cd Projekt
          docker build -t $IMAGE .
          docker push $IMAGE
