name: CI — Build, Test, Push, Deploy

on:
  push:
    branches:
      - project/422385

permissions:
  id-token: write
  contents: read

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    environment: "422385"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install flask pytest

      - name: Run tests
        run: pytest Projekt/solution/tests/ -v

      - name: Zaloguj się do Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_422385 }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_422385 }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_422385 }}

      - name: Zaloguj się do ACR
        run: az acr login --name acrlab04422385

      - name: Zbuduj i wypchnij obraz
        run: |
          IMAGE=acrlab04422385.azurecr.io/app:${{ github.sha }}
          docker build -t $IMAGE Projekt/solution/
          docker push $IMAGE

      - name: Pobierz kubeconfig AKS
        run: |
          az aks get-credentials \
            --resource-group devops422385-gha-rg \
            --name aks-lab04 \
            --overwrite-existing

      - name: Zaktualizuj obraz w AKS
        run: |
          kubectl set image deployment/app \
            app=acrlab04422385.azurecr.io/app:${{ github.sha }}
          kubectl rollout status deployment/app --timeout=120s