name: Lab 9 Matrix CI 419845

on:
  push:
    branches:
      - lab_9/new_branch_419845

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test with Python ${{ matrix.python-version }}
        uses: ./.github/actions/test-python-env-419845
        with:
          python-version: ${{ matrix.python-version }}
          app-path: Lab_9/app_419845