name: CI

on:
  push:
    branches:
      - lab_7/new_branch_419371

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Lab_7/app_419371/requirements.txt

      - name: Start Flask app
        run: |
          python Lab_7/app_419371/calculator.py &
          sleep 5

      - name: Run tests
        run: |
          cd Lab_7/app_419371
          python -m pytest test_calculator.py -v