name: CI

on:
  push:
    branches:
      - lab_8/new_branch_422364

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r Lab_8/app_422364/requirements.txt

      - name: Run app in background
        run: |
          python Lab_8/app_422364/app.py &
          for i in {1..10}; do
            curl -s http://localhost:5000/health && break
            sleep 2
          done

      - name: Run tests
        run: python -m pytest Lab_8/app_422364/test_app.py -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_422364 }}
          password: ${{ secrets.DOCKERHUB_TOKEN_422364 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: Lab_8/app_422364
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_422364 }}/lab8-app-422364:latest