name: CI

on:
  push:
    branches:
      - 'lab_7/new_branch_415942'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask pytest requests

      - name: Run Flask server and execute tests
        run: |
          cd Lab_7/app_415942
          
          # Uruchomienie serwera w tle (znak '&' na końcu)
          python calculator.py &
          
          # Krótkie opóźnienie, aby dać serwerowi czas na start
          sleep 2
          
          # Uruchomienie testów
          python -m pytest test_calculator.py -v