name: CI_419845  

on:
  push:
    branches:
      - lab_7/new_branch_419845 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests pytest  

      - name: Run tests
        run: |
          cd Lab_7/app_419845  
          python calculator.py &  
          sleep 2                
          python -m pytest test_calculator.py -v